### ISSUE TITLE
Can I use mz0c or mz7c to compress mz-800 basic mz-1z016.mzf ?

### ISSUE THREAD

**Issue by rcmolina** [SHARPENTIERS/mz0#1]
No luck.. I suspect that is something related to addrs. After compressing the file, can' load the compressed file,

**Comment by hlide** [comment]
Sorry for the long answer. I was able to compress a BASIC for MZ-700 but I never tested for the rest of BASICs. If MZ-1Z016.mzf is a BASIC for MZ-800 in its native mode, it may not work indeed.
